### ISSUE TITLE
OTA GUI always fails to flash and throws the same error each time

### ISSUE THREAD

**Issue by Sky7734** [ButterscotchV/SlimeVR-OTA-CLI#3]
### No matter what I try the GUI tool (CLI tool untested) it always throws the exact same error on both official and DIY Slimes under different conditions despite following the instructions and more.

To clarify I'm using Windows 11 24H2 and so far all the steps I've tried are as follows: Restarting my PC, Running app as admin, connecting multiple and singular tracker at once, tried different networks, trying with and without SlimeVR server running, tried different firmware version just in case, and tried running with and without USB cable attached.

I can ping from command prompt and SlimeVR works just fine on currently installed firmware so it's definitely not a connection issue.

I'm copy pasting the error here but I'll also attach a screenshot of it:

```
SlimeVrOta.OtaException: No response from device.
 ---> System.OperationCanceledException: The operation was canceled.
   at System.Threading.CancellationToken.ThrowOperationCanceledException()
   at System.Threading.CancellationToken.ThrowIfCancellationRequested()
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.ThrowException(SocketError, CancellationToken)
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.System.Threading.Tasks.Sources.IValueTaskSource<System.Net.Sockets.Socket>.GetResult(Int16)
   at System.Net.Sockets.TcpListener.<AcceptTcpClientAsync>g__WaitAndWrap|32_0(ValueTask`1)
   at SlimeVrOta.EspOta.Serve(IPEndPoint, IPEndPoint, String, Byte[], String , OtaCommands , IProgress`1 , CancellationToken )
   --- End of inner exception stack trace ---
   at SlimeVrOta.EspOta.Serve(IPEndPoint, IPEndPoint, String, Byte[], String , OtaCommands , IProgress`1 , CancellationToken )
   at SlimeVrOta.Gui.MainWindow.FlashFirmware(Object sender, RoutedEventArgs e)
```

![image](https://github.com/user-attachments/assets/041b2cc2-1886-414d-b542-fb21da2215fd)

**Comment by ButterscotchV** [comment]
Did you start flashing within 1 minute of turning your tracker on?

**Comment by Sky7734** [comment]
Yes I forgot to mention that. I tried both within just a few seconds of turning it on and after a few minutes of having it on.

**Comment by Sky7734** [comment]
Seems to be fixed in one of the newer updates so I'm closing the issue.
